src/main/java/com/gedim/playground/business/author/entity/Author.java
package com.gedim.playground.business.author.entity;

import com.gedim.playground.business.base.entity.BaseEntity;
import com.gedim.playground.business.post.entity.Post;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

@Entity
@XmlRootElement
public class Author extends BaseEntity {

    @Column(length = 255, nullable = false)
    private String name;
    
    @Column(length = 255, nullable = false)
    private String email;
    
    @OneToMany(mappedBy = "author")
    private List<Post> posts;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @XmlTransient
    public List<Post> getPosts() {
        return posts;
    }

    public void setPosts(List<Post> posts) {
        this.posts = posts;
    }

}

src/main/java/com/gedim/playground/business/base/entity/BaseEntity.java
package com.gedim.playground.business.base.entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import java.io.Serializable;

/**
 * Entity implementation class for Entity: BaseEntity
 */
@MappedSuperclass
public class BaseEntity implements Serializable {

    private static final long serialVersionUID = -7368158935860299361L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    public BaseEntity() {
        super();
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}

src/main/java/com/gedim/playground/business/post/entity/Post.java
package com.gedim.playground.business.post.entity;

import com.gedim.playground.business.author.entity.Author;
import com.gedim.playground.business.base.entity.BaseEntity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Temporal;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

@Entity
@NamedQueries(value = {
    @NamedQuery(name = "getAllPostsWithAuthors", query = "select post from Post post left join fetch post.author"),
    @NamedQuery(name = "getPostById", query = "select post from Post post left join fetch post.author where post.id =:postId")
})
@XmlRootElement
public class Post extends BaseEntity {

    @Column(length = 255, nullable = false)
    private String title;
    
    @Column(length = 4000, nullable = false)
    private String content;
    
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date posted;
    
    @ManyToOne
    @XmlTransient
    private Author author;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getPosted() {
        return posted;
    }

    public void setPosted(Date posted) {
        this.posted = posted;
    }

    public Author getAuthor() {
        return author;
    }

    public void setAuthor(Author author) {
        this.author = author;
    }

}

src/main/java/com/gedim/playground/presentation/author/AuthorBean.java
package com.gedim.playground.presentation.author;

import java.io.Serializable;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class AuthorBean implements Serializable {

    public String getGravatarImageUrl(String email) {
        String gravUrl = "";
        try {
            byte[] bytesOfMessage = email.getBytes("UTF-8");

            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] thedigest = md.digest(bytesOfMessage);
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < thedigest.length; ++i) {
                sb.append(Integer.toHexString((thedigest[i] & 0xFF) | 0x100).substring(1, 3));
            }
            gravUrl = sb.toString();
        } catch (NoSuchAlgorithmException | UnsupportedEncodingException ex) {
            // TODO: add slf4j logging
            Logger.getLogger(AuthorBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "http://www.gravatar.com/avatar/" + gravUrl;
    }
}

src/main/java/com/gedim/playground/presentation/post/PostBean.java
package com.gedim.playground.presentation.post;

import com.gedim.playground.business.post.boundary.PostFacade;
import com.gedim.playground.business.post.entity.Post;
import java.io.Serializable;
import java.util.List;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;

@Named
@ViewScoped
@Path("/posts")
public class PostBean implements Serializable {
    
    @Inject
    PostFacade postFacade;

    private List<Post> posts;
    private Post post = new Post();

    public void loadPost() {
        post = postFacade.getPostById(post.getId());
    }
    
    public void loadPosts() {
        getPosts();
    }

    @GET
    public List<Post> getPosts() {
        if (posts == null) {
            posts = postFacade.getAllPostsWithAuthors();
        }
        return posts;
    }

    @GET
    @Path("{id}")
    public Post getPost(@PathParam("id") Long id) {
        return postFacade.getPostById(id);
    }

    public Post getPost() {
        return post;
    }
}

src/main/java/com/gedim/playground/presentation/util/TimeBean.java
package com.gedim.playground.presentation.util;

import java.io.Serializable;
import java.util.Date;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@ViewScoped
@Named
public class TimeBean implements Serializable {

    public Date getNow() {
        return new Date();
    }
}

src/main/webapp/WEB-INF/templates/debug.xhtml
<f:view xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:form>
        <div>
            <h:messages/>
        </div>
        <div>
            <ui:debug/>
        </div>
    </h:form>

</f:view>

src/main/webapp/WEB-INF/templates/footer.xhtml
<f:view xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets">

    <div class="container">
        <hr />
        <h5><small>rendered at #{timeBean.now}</small></h5>
        <h5><small>#{view.viewId}</small></h5>
    </div>

</f:view>

src/main/webapp/WEB-INF/templates/header.xhtml
<f:view xmlns="http://www.w3.org/1999/xhtml"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:h="http://java.sun.com/jsf/html">

    <nav class="navbar navbar-default">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h:link class="navbar-brand" outcome="index" value="playground" />
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="#{view.viewId eq '/index.xhtml' ? 'active' : ''}"><h:link outcome="index" value="Home"/></li>
                    <li class="#{view.viewId eq '/post/posts.xhtml' ? 'active' : ''}"><h:link outcome="posts" value="Microblog" /></li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search" />
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>
    </nav>

</f:view>

src/main/webapp/WEB-INF/templates/layout.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

  <h:head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>playground</title>

    <h:outputStylesheet library="webjars" name="bootstrap/3.3.4/dist/css/bootstrap.min.css" />
    <h:outputStylesheet library="webjars" name="bootstrap/3.3.4/dist/css/bootstrap-theme.min.css" />
    <h:outputStylesheet library="playground/css" name="playground.css" />

    <h:outputScript library="webjars" name="jquery/2.1.3/dist/jquery.min.js"/>
    <h:outputScript library="webjars" name="bootstrap/3.3.4/dist/js/bootstrap.min.js"/>
    <h:outputScript library="javax.faces" name="jsf.js"/>

    <ui:insert name="scripts"/>
  </h:head>

  <h:body>

    <ui:param name="siteRoot"
              value="#{facesContext.externalContext.requestContextPath}"/>

    <ui:include src="/WEB-INF/templates/header.xhtml"/>

    <ui:insert name="content"/>

    <ui:include src="/WEB-INF/templates/footer.xhtml"/>

    <ui:include src="/WEB-INF/templates/debug.xhtml"/>

  </h:body>
</html>

src/main/webapp/index.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="content">

        <div class="container">

            <div class="row">
                <div class="col-md-4">
                    <h4>JSF 2.2</h4>
                    <p>Developed through the Java Community Process under JSR - 314, JavaServer Faces technology establishes the standard for building server-side user interfaces.</p>
                </div>
                <div class="col-md-4">
                    <h4>EJB 3.2</h4>
                    <p>Enterprise JavaBeans (EJB) technology is the server-side component architecture for Java Platform, Enterprise Edition (Java EE). EJB technology enables rapid and simplified development of distributed, transactional, secure and portable applications based on Java technology.</p>
                </div>
                <div class="col-md-4">
                    <h4>JPA 2.1</h4>

                    <p>The Java Persistence API is a Java programming language framework managing relational data in applications using Java Platform, Standard Edition and Java Platform, Enterprise Edition.</p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <h4>Hibernate 4.3</h4>
                    <p>Hibernate an open source Java persistence framework project. Perform powerful object relational mapping and query databases using HQL and SQL.</p>
                </div>
                <div class="col-md-4">
                    <h4>EhCache</h4>
                    <p>Ehcache is an open source, standards-based cache used to boost performance, offload the database and simplify scalability. Ehcache is robust, proven and full-featured and this has made it the most widely-used Java-based cache.</p>
                </div>
                <div class="col-md-4">
                    <h4>Elastic Search</h4>
                    <p>ElasticSearch is a distributed RESTful search engine built for the cloud.</p>
                </div>
            </div>

        </div>

    </ui:define>

</ui:composition>

src/main/webapp/post/post.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:pg="http://java.sun.com/jsf/composite/playground"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="content">

        <f:metadata>
            <f:viewParam name="postId" value="#{postBean.post.id}" />
            <f:viewAction action="#{postBean.loadPost}" />
        </f:metadata>

        <div class="container">
            <h:form>
                <div>#{postBean.post.author.name}</div>
                <div>#{postBean.post.title}</div>
                <div>#{postBean.post.content}</div>
                <div><pg:gravatar email="#{post.author.email}" /></div>
            </h:form>
        </div>

    </ui:define>

</ui:composition>

src/main/webapp/post/posts.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:pg="http://java.sun.com/jsf/composite/playground"
                template="/WEB-INF/templates/layout.xhtml">
    <ui:define name="content">

        <f:metadata>
            <f:viewAction action="#{postBean.loadPosts}" />
        </f:metadata>

        <div class="container">
            <h:form>
                <table class="table table-striped">
                    <thead>
                        <td>#</td>
                        <td>Title</td>
                        <td>Content</td>
                        <td>Author</td>
                        <td>Image</td>
                    </thead>
                    <tbody>
                        <ui:repeat value="#{postBean.posts}" var="post">
                            <tr>
                                <td>#{post.id}</td>
                                <td><a href="/post/post.jsf?postId=#{post.id}">#{post.title}</a></td>
                                <td>#{post.content}</td>
                                <td>#{post.author.name}</td>
                                <td><pg:gravatar email="#{post.author.email}" /></td>
                            </tr>
                        </ui:repeat>
                    </tbody>
                </table>
            </h:form>

        </div>

    </ui:define>
</ui:composition>

src/main/webapp/resources/playground/gravatar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite">

    <cc:interface>
        <cc:attribute name="email" type="java.lang.String"/>
    </cc:interface>

    <cc:implementation>
        <img src="#{authorBean.getGravatarImageUrl(cc.attrs.email)}" />
    </cc:implementation>
</html>